{% set name = "DataProfiler" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/DataProfiler-{{ version }}.tar.gz
  sha256: 86567eb60c07a59087025f806ddaf8230f92df89bfd26a79ad7486599620e168

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    # This package imports itself at build time these are not needed. Open an issue upstream to avoid this.
    - h5py >=2.10.0
    - wheel >=0.33.1
    - numpy >=1.22.0
    - pandas >=1.1.2
    - python-dateutil >=2.7.5
    - pytz >=2020.1
    - pyarrow >=1.0.1
    - chardet >=3.0.4
    - fastavro >=1.0.0
    - python-snappy >=0.5.4
    - charset-normalizer >=1.3.6
    - psutil >=4.0.0
    - scipy >=1.10.0
    - requests >=2.28.1
    - networkx >=2.5.1
    - typing-extensions >=3.10.0.2
    - hll >=2.0.3
    - datasketches >=4.1.0
    - packaging >=23.0
    - boto3 >=1.28.61

  run:
    #### requirements.txt
    - typing_extensions >=3.10.0.2
    - versioneer
    - python >={{ python_min }}
    - h5py >=2.10.0
    - wheel >=0.33.1
    - numpy <2.0.0
    - pandas >=1.1.2
    - python-dateutil >=2.7.5
    - pytz >=2020.1
    - pyarrow >=1.0.1
    - chardet >=3.0.4
    - fastavro >=1.1.0
    - python-snappy >=0.7.1
    - charset-normalizer >=1.3.6
    - psutil >=4.0.0
    - scipy >=1.10.0
    - requests ==2.32.*
    - networkx >=2.5.1
    - typing-extensions >=3.10.0.2
    - hll >=2.0.3
    - datasketches >=4.1.0
    - packaging >=23.0
    - boto3 >=1.28.61

test:
  imports:
    - dataprofiler
    - resources
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/capitalone/data-profiler
  summary: What is in your data? Detect schema, statistics and entities in almost any file.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
