{% set name = "DataProfiler" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/DataProfiler-{{ version }}.tar.gz
  sha256: 04813e6b8a89f207c3698d04f42882cbbb662feef2fff6935b9aa1554afec483

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
# This package imports itself at build time these are not needed. Open an issue upstream to avoid this.
    - h5py >=2.10.0
    - wheel >=0.33.1
    - numpy >=1.20.0
    - pandas >=1.1.2
    - python-dateutil >=2.7.5
    - pytz >=2020.1
    - pyarrow >=1.0.1
    - chardet >=3.0.4
    - fastavro >=1.0.0
    - python-snappy >=0.5.4
    - charset-normalizer >=1.3.6
    - psutil >=4.0.0
    - scipy >=1.4.1
    - requests >=2.28.1
    - networkx >=2.5.1
    - typing-extensions >=3.10.0.2
    - hll >=2.0.3
    - datasketches >=4.1.0
    - packaging >=23.0

  run:
#### requirements.txt
    - python >=3.7
    - h5py >=2.10.0
    - wheel >=0.33.1
    - numpy >=1.20.0
    - pandas >=1.1.2
    - python-dateutil >=2.7.5
    - pytz >=2020.1
    - pyarrow >=1.0.1
    - chardet >=3.0.4
    - fastavro >=1.0.0
    - python-snappy >=0.5.4
    - charset-normalizer >=1.3.6
    - psutil >=4.0.0
    - scipy >=1.4.1
    - requests >=2.28.1
    - networkx >=2.5.1
    - typing-extensions >=3.10.0.2
    - hll >=2.0.3
    - datasketches >=4.1.0
    - packaging >=23.0

test:
  imports:
    - dataprofiler
    - resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/capitalone/data-profiler
  summary: What is in your data? Detect schema, statistics and entities in almost any file.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
