{% set name = "DataProfiler" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/DataProfiler-{{ version }}.tar.gz
  sha256: ad07fbb0256863ec98ba9fec0d80f6a998e07de3ffd7dbdeafc6827d91b92245

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
# This package imports itself at build time these are not needed. Open an issue upstream to avoid this.
    - h5py >=2.10.0
    - wheel >=0.33.1
#    - future >=0.18.2
    - numpy >=1.20.0
    - pandas >=1.1.2
    - python-dateutil >=2.7.5
    - pytz >=2020.1
    - pyarrow >=1.0.1
    - chardet >=3.0.4
    - fastavro >=1.0.0
    - python-snappy >=0.5.4
    - charset-normalizer >=1.3.6
    - psutil >=4.0.0
    - scipy >=1.4.1
    - requests >=2.28.1
    - networkx >=2.5.1
    - typing-extensions >=3.10.0.2
  run:
#### requirements.txt
    - python >=3.7
    - setuptools
    - h5py >=2.10.0
    - wheel >=0.33.1
#    - future >=0.18.2
    - numpy >=1.20.0
    - pandas >=1.1.2
    - python-dateutil >=2.7.5
    - pytz >=2020.1
    - pyarrow >=1.0.1
    - chardet >=3.0.4
    - fastavro >=1.0.0
    - python-snappy >=0.5.4
    - charset-normalizer >=1.3.6
    - psutil >=4.0.0
    - scipy >=1.4.1
    - requests >=2.28.1
    - networkx >=2.5.1
    - typing-extensions >=3.10.0.2

test:
  imports:
    - dataprofiler

about:
  home: https://github.com/capitalone/data-profiler
  summary: What is in your data? Detect schema, statistics and entities in almost any file.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
